version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "scheduled-sentiment"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ispjlxpqay0n"
s3_prefix = "scheduled-sentiment"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Table=\"News\" Topic=\"Happy-News\" Region=\"us-east-1\""
image_repositories = []
