AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  image-thumbnail-python

  Sample SAM Template for image-thumbnail-python

Globals:
  Function:
    Timeout: 60
    CodeUri: handler/
    Runtime: python3.9
    MemorySize: 128
    Architectures:
      - x86_64
    Environment:
      Variables:
        THUMBNAIL_SIZE: 128
        REGION_NAME: "us-east-1"
        DYNAMODB_TABLE: !Ref ImagesDynamoDBTable
    Layers:
      - "arn:aws:lambda:us-east-1:770693421928:layer:Klayers-p39-pillow:1"

Resources:
  CreateThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler_s3_thumbnail_generator
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImagesDynamoDBTable
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "s3:*"
              Resource: "*"
      Events:
        CreateThumbnailEvent:
          Type: S3
          Properties:
            Bucket: !Ref SrcBucket
            Events: s3:ObjectCreated:*

  GetThumbnail:
      Type: AWS::Serverless::Function
      Properties:
        Handler: app.s3_get_item
        Policies: 
          - DynamoDBReadPolicy:
              TableName: !Ref ImagesDynamoDBTable
        Events:
          GetThumbnailEvent:
            Type: Api
            Properties:
              Path: /images/{id}
              Method: GET   

  ListThumbnails:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler_s3_get_thumbnail_urls
      Policies: 
        - DynamoDBReadPolicy:
            TableName: !Ref ImagesDynamoDBTable
      Events:
        ListThumbnailsEvent:
          Type: Api
          Properties:
            Path: /images
            Method: GET 
      
  SrcBucket:
    Type: AWS::S3::Bucket

  ImagesDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: "images-url-tables"
# Outputs:
#   ThumbnailApi:
#     Description: "API Gateway endpoint URL for Prod stage for Thumbnail Generator function"
#     Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/images/"
#   CreateThumbnailFunction:
#     Description: "CreateThumbnailFunction Lambda Function ARN"
#     Value: !GetAtt CreateThumbnailFunction.Arn
# HelloWorldFunctionIamRole:
#   Description: "Implicit IAM Role created for Hello World function"
#   Value: !GetAtt HelloWorldFunctionRole.Arn
