version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "face-rekognition"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ispjlxpqay0n"
s3_prefix = "face-rekognition"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Table=\"Faces\" Region=\"us-east-1\""
image_repositories = []
